# Telar - Digital Storytelling Framework
# https://github.com/UCSB-AMPLab/telar

# Site Settings
title: Andean Object Stories
description: "Researching Stories through THINGS. How can we learn from things? What stories do they tell us about the past? This digital exhibit series tells stories from works in the Andean Region of South America now in UC Santa Barbara's Art, Architecture, and Design Museum. "
baseurl: "/telar-khipu"
url: "https://up-in-the-clouds.github.io"
author: ""
email: ""
telar_theme: "santa-barbara" # Options: paisajes, neogranadina, santa-barbara, austin, or custom
logo: "" # Path to logo image (optional)

# Google Sheets Integration (optional)
# Manage content via Google Sheets instead of editing CSV files directly.
# See docs/google_sheets_integration/README.md for detailed setup instructions.
#
# Setup:
# 1. Get the template:
#    - Option A: Duplicate our template at https://bit.ly/telar-template
#    - Option B: Import docs/google_sheets_integration/telar-template.xlsx to Google Sheets yourself
# 2. Share your sheet: Anyone with the link (Viewer access)
# 3. Publish your sheet: File > Share > Publish to web
# 4. Paste both URLs below
# 5. Set enabled: true
# 6. Commit changes
#    - If using GitHub Pages: GitHub Actions will automatically discover tab GIDs and fetch CSVs
#    - If running locally: Run `python3 scripts/fetch_google_sheets.py` before building
google_sheets:
  enabled: true
  shared_url: "https://docs.google.com/spreadsheets/d/1nOFRgHwzp2zEmAszYC7o3cT63At_gQBBACGLfJwFCwc/edit"
  published_url: "https://docs.google.com/spreadsheets/d/e/2PACX-1vSMmpcjrRDV7pxg2Gzm6FL-7YAx1XYUV9DfIvz_7QmNq_acGmi9SqO0g6G3pDh_itcjp_v2y9Rus54s/pubhtml"

#
#
#
# PLEASE DO NOT EDIT BELOW THIS LINE UNLESS YOU KNOW WHAT YOU ARE DOING
#
#
#

# Collections
collections:
  stories:
    output: true
    permalink: /stories/:name/
  objects:
    output: true
    permalink: /objects/:name/
  glossary:
    output: true
    permalink: /glossary/:name/

# Collections Directory (a folder where Jekyll and the Telar scripts will put all auto-generated object and story working files)
collections_dir: _jekyll-files

# Build Settings
markdown: kramdown
permalink: pretty
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .github
  - README.md
  - docs/
  - scripts/

# Defaults
defaults:
  - scope:
      path: ""
      type: "stories"
    values:
      layout: "story"
  - scope:
      path: ""
      type: "objects"
    values:
      layout: "object"
  - scope:
      path: ""
      type: "glossary"
    values:
      layout: "glossary"

# Tell Jekyll not to expect dates for these collections
future: true
show_drafts: false

# Telar Settings (version information)
telar:
  version: "0.3.1-beta"
  release_date: "2025-10-26"

# OpenSeadragon Settings
openseadragon:
  prefixUrl: "/assets/images/openseadragon/"
  minZoomLevel: 0
  maxZoomLevel: 5
  animationTime: 1.5
  visibilityRatio: 1.0

# Plugins
plugins:
  - jekyll-seo-tag

# WEBrick server configuration for development (enables CORS for IIIF)
webrick:
  headers:
    Access-Control-Allow-Origin: "*"
    Access-Control-Allow-Methods: "GET, POST, OPTIONS"
    Access-Control-Allow-Headers: "Content-Type"
